language: java
jdk:
  - oraclejdk8
  - openjdk7
os:
  - linux
  - osx
env:
  - PROJECT_VERSION=0.0.1
addons:
  firefox: "17.0"
  go: "1.0.3"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - echo $JAVA_HOME
  - echo $PROJECT_VERSION
  - echo $TRAVIS_OS_NAME
script:
  - jdk_switcher use oraclejdk8
  - echo $JAVA_HOME
  - jdk_switcher use openjdk7
  - echo $JAVA_HOME
