language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Wh0/vC2HpV2SbxBP037t3279t9aV1QkF9wSke7P4OKtDzoRyUIE//lsionZCAxmpHoV+onuE1waKJvmPBevX1iK4V4t3ANfuxcvpLoq/aWdXxagLXtuVm13gvi3/y6mzYmCiAqfgd7Ow53aFnwi4yWKEMXXVzMbRI5VqjUbFqFh2VBGuz8tx0PNqUEYuo+vDllj/yMQcCW0iPfMJyBAA2xudHNgqcvahTD42nTnQBqY4KKhmhhR0XV5P8dr34RSjR6OHms/aZ8JxlApzKQ/mM/GiZjgXGRETj9MG/Dj0ipQAcHKimf7u+gKs9bi+GscqcJ74nRPZJid5DlkVMyeT1Edm1UQS5CxKCtVkOGxOmHuQxk2ojbAfiXem4NC8gObb6jNndYSEkxpwD9xgldWui8N7OwvDU3d7GAML9252V6DhwMOkAxo21fKf8DtzvbWZ0Iu+9AUSncZa8gU9ZIhIZHI8rjbYg6fui2v9Fmsls3VtcKy4Qh+qKd7HDBfISCVqBL7eXmdmrSQCfSOSnVhMG3arVPCwwZGrG4ts9sdUv3gheeuARnsIG8XVpCpHhDVLTtldFBe78/pdqzIfIndlSQhB3s3OiK2Shq3MaZ5LHSZK8s5/e5DN1VylTakJPq1qKbEYQhfhbaihe/ZxG50+6eLuxjgycpzOITLOHPdStrQ=
